services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - ${PORT_DB}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: [dev, production]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles: [dev]

  api:
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      PORT_DB: ${PORT_DB}
      PORT_API: ${PORT_API}
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - ${PORT_API}:3000
    profiles: [production]

  bot:
    restart: always
    depends_on:
      - api
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    profiles: [production]

  sender:
    restart: always
    depends_on:
      - api
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: .
      dockerfile: Dockerfile
      target: sender
    profiles: [production]

volumes:
  pgdata:
