services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: [dev, production]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles: [dev]

  api:
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE: /${DATABASE}
    volumes:
      - ${DATABASE}:/${DATABASE}
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - 3000:3000
    profiles: [production]

  bot:
    restart: always
    depends_on:
      - api
    volumes:
      - ${DATABASE}:/${DATABASE}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE: /${DATABASE}
    build:
      context: .
      dockerfile: Dockerfile
      target: bot
    profiles: [production]

  sender:
    restart: always
    depends_on:
      - api
    volumes:
      - ${DATABASE}:/${DATABASE}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE: /${DATABASE}
    build:
      context: .
      dockerfile: Dockerfile
      target: sender
    profiles: [production]

volumes:
  pgdata:
